CREATE
OR        REPLACE FUNCTION FN_CARD_LIST (p_id INT) RETURNS TABLE (card_id INT) AS $$
BEGIN
    RETURN QUERY
    SELECT A.card_id FROM ACCOUNT_CARD_HAVE A WHERE A.account_id = p_id;
END
$$ LANGUAGE plpgsql;

CREATE
OR        REPLACE FUNCTION FN_CARD_LIST () RETURNS TABLE (card_id INT) AS $$
BEGIN
    RETURN QUERY
    SELECT A.card_id FROM ACCOUNT_CARD_HAVE A;
END
$$ LANGUAGE plpgsql;

SELECT    *
FROM      FN_CARD_LIST (1);