CREATE    DOMAIN TYPE_NAME_ACCOUNT VARCHAR(60);

CREATE    DOMAIN TYPE_NAME_CATEGORY VARCHAR(20) CHECK (VALUE = UPPER(VALUE));

CREATE    DOMAIN TYPE_NAME_EXAM VARCHAR(60);

CREATE    DOMAIN TYPE_NAME_FILE VARCHAR(60);