CREATE
OR        REPLACE FUNCTION FN_SESSION_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('SESS', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_CATEGORY_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('CATE', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_CARD_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('CARD', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_COMPONENT_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('COMP', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ACCOUNT_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('ACNT', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_SESSION (p_session_id TYPE_ID) RETURNS INT AS $$
BEGIN
    RETURN CAST(SUBSTRING(p_session_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_CATEGORY (p_category_id TYPE_ID) RETURNS INT AS $$
BEGIN
    RETURN CAST(SUBSTRING(p_category_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_CARD (p_card_id TYPE_ID) RETURNS INT AS $$
BEGIN
    RETURN CAST(SUBSTRING(p_card_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_COMPONENT (p_component_id TYPE_ID) RETURNS INT AS $$
BEGIN
    RETURN CAST(SUBSTRING(p_component_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_ACCOUNT (p_account_id TYPE_ID) RETURNS INT AS $$
BEGIN
    RETURN CAST(SUBSTRING(p_account_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;