CREATE
OR        REPLACE FUNCTION FN_SESSION_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('SESS', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_CATEGORY_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('CATE', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_CARD_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('CARD', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_COMPONENT_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('COMP', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ACCOUNT_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('ACNT', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_EXAM_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('EXAM', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_QUIZ_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('QUIZ', TO_CHAR(p_id, 'FM00000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_LOG_ID (p_id INT) RETURNS TYPE_ID AS $$ 
    SELECT CONCAT('LOG', TO_CHAR(p_id, 'FM000000000000'));
$$ LANGUAGE SQL IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_SESSION (p_session_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_session_id, 1, 4) <> 'SESS' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_session_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_CATEGORY (p_category_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_category_id, 1, 4) <> 'CATE' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_category_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_CARD (p_card_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_card_id, 1, 4) <> 'CARD' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_card_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_COMPONENT (p_component_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_component_id, 1, 4) <> 'COMP' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_component_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_ACCOUNT (p_account_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_account_id, 1, 4) <> 'ACNT' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_account_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_EXAM (p_exam_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_exam_id, 1, 4) <> 'EXAM' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_exam_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_QUIZ (p_quiz_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_quiz_id, 1, 4) <> 'QUIZ' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_quiz_id FROM 5) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE
OR        REPLACE FUNCTION FN_ID_LOG (p_log_id TYPE_ID) RETURNS INT AS $$
BEGIN
    IF SUBSTRING(p_log_id, 1, 3) <> 'LOG' THEN
        RETURN NULL;
    END IF;
    RETURN CAST(SUBSTRING(p_log_id FROM 4) AS INT);
END;
$$ LANGUAGE plpgsql IMMUTABLE;