-- Categories
SELECT    FN_CATEGORY_INSERT (NULL, 'ACTIONS');

-- 1
SELECT    FN_CATEGORY_INSERT (NULL, 'THINKING');

-- 2
SELECT    FN_CATEGORY_INSERT (NULL, 'COMMUNICATION');

-- 3
SELECT    FN_CATEGORY_INSERT (NULL, 'DECISIONS');

-- 4
SELECT    FN_CATEGORY_INSERT (NULL, 'PEOPLE');

-- 5
SELECT    FN_CATEGORY_INSERT (NULL, 'SOCIETY');

-- 6
SELECT    FN_CATEGORY_INSERT (NULL, 'QUALITIES');

-- 7
SELECT    FN_CATEGORY_INSERT (NULL, 'CHANGE');

-- 8
SELECT    FN_CATEGORY_INSERT (NULL, 'POSSIBILITY');

-- 9
SELECT    FN_CATEGORY_INSERT (NULL, 'CONCEPTS');

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(1), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(2), ARRAY[FN_CATEGORY_ID(4)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(3), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(4), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(5), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(6), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(7), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(8), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(9), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(10), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(11), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(12), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(13), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(14), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(15), ARRAY[FN_CATEGORY_ID(4)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(16), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(17), ARRAY[FN_CATEGORY_ID(2)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(18), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(19), ARRAY[FN_CATEGORY_ID(2)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(20), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(21), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(22), ARRAY[FN_CATEGORY_ID(2)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(23), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(24), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(25), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(26), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(27), ARRAY[FN_CATEGORY_ID(4)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(28), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(29), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(30), ARRAY[FN_CATEGORY_ID(8)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(31), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(32), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(33), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(34), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(35), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(36), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(37), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(38), ARRAY[FN_CATEGORY_ID(8)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(39), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(40), ARRAY[FN_CATEGORY_ID(8)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(41), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(42), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(43), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(44), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(45), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(46), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(47), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(48), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(49), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(50), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(51), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(52), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(53), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(54), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(55), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(56), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(57), ARRAY[FN_CATEGORY_ID(2)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(58), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(59), ARRAY[FN_CATEGORY_ID(4)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(60), ARRAY[FN_CATEGORY_ID(8)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(61), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(62), ARRAY[FN_CATEGORY_ID(8)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(63), ARRAY[FN_CATEGORY_ID(8)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(64), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(65), ARRAY[FN_CATEGORY_ID(2)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(66), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(67), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(68), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(69), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(70), ARRAY[FN_CATEGORY_ID(1)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(71), ARRAY[FN_CATEGORY_ID(8)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(72), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(73), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(74), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(75), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(76), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(77), ARRAY[FN_CATEGORY_ID(2)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(78), ARRAY[FN_CATEGORY_ID(4)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(79), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(80), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(81), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(82), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(83), ARRAY[FN_CATEGORY_ID(3)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(84), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(85), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(86), ARRAY[FN_CATEGORY_ID(10)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(87), ARRAY[FN_CATEGORY_ID(2)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(88), ARRAY[FN_CATEGORY_ID(6)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(89), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(90), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(91), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(92), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(93), ARRAY[FN_CATEGORY_ID(9)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(94), ARRAY[FN_CATEGORY_ID(5)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(95), ARRAY[FN_CATEGORY_ID(4)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(96), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(97), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(98), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(99), ARRAY[FN_CATEGORY_ID(7)]);

SELECT CATEGORY_TO_CARD_CATEGORIZE(FN_CARD_ID(100), ARRAY[FN_CATEGORY_ID(7)]);

-- Follow dummy: account 1 (tester) follows a category they have and one they don't.
SELECT    FN_CATEGORY_INSERT (2, 'OTHER_OWNER_CATEGORY');

SELECT    CATEGORY_FOLLOW (FN_ACCOUNT_ID(1), FN_CATEGORY_ID(1));  -- category 1 (ACTIONS): account 1 has cards in it
SELECT    CATEGORY_FOLLOW (FN_ACCOUNT_ID(1), FN_CATEGORY_ID(11)); -- category 11 (OTHER_OWNER_CATEGORY, owned by account 2): account 1 does not have it