-- Categories
SELECT    FN_CATEGORY_INSERT (NULL, 'ACTIONS');

-- 1
SELECT    FN_CATEGORY_INSERT (NULL, 'THINKING');

-- 2
SELECT    FN_CATEGORY_INSERT (NULL, 'COMMUNICATION');

-- 3
SELECT    FN_CATEGORY_INSERT (NULL, 'DECISIONS');

-- 4
SELECT    FN_CATEGORY_INSERT (NULL, 'PEOPLE');

-- 5
SELECT    FN_CATEGORY_INSERT (NULL, 'SOCIETY');

-- 6
SELECT    FN_CATEGORY_INSERT (NULL, 'QUALITIES');

-- 7
SELECT    FN_CATEGORY_INSERT (NULL, 'CHANGE');

-- 8
SELECT    FN_CATEGORY_INSERT (NULL, 'POSSIBILITY');

-- 9
SELECT    FN_CATEGORY_INSERT (NULL, 'CONCEPTS');

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (1, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (2, ARRAY[4]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (3, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (4, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (5, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (6, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (7, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (8, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (9, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (10, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (11, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (12, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (13, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (14, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (15, ARRAY[4]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (16, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (17, ARRAY[2]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (18, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (19, ARRAY[2]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (20, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (21, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (22, ARRAY[2]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (23, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (24, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (25, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (26, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (27, ARRAY[4]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (28, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (29, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (30, ARRAY[8]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (31, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (32, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (33, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (34, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (35, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (36, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (37, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (38, ARRAY[8]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (39, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (40, ARRAY[8]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (41, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (42, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (43, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (44, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (45, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (46, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (47, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (48, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (49, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (50, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (51, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (52, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (53, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (54, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (55, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (56, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (57, ARRAY[2]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (58, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (59, ARRAY[4]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (60, ARRAY[8]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (61, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (62, ARRAY[8]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (63, ARRAY[8]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (64, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (65, ARRAY[2]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (66, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (67, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (68, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (69, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (70, ARRAY[1]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (71, ARRAY[8]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (72, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (73, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (74, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (75, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (76, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (77, ARRAY[2]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (78, ARRAY[4]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (79, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (80, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (81, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (82, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (83, ARRAY[3]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (84, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (85, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (86, ARRAY[10]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (87, ARRAY[2]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (88, ARRAY[6]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (89, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (90, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (91, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (92, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (93, ARRAY[9]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (94, ARRAY[5]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (95, ARRAY[4]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (96, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (97, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (98, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (99, ARRAY[7]);

CALL      PR_CATEGORY_TO_CARD_CATEGORIZE (100, ARRAY[7]);

-- Follow dummy: account 1 (tester) follows a category they have and one they don't.
SELECT    FN_CATEGORY_INSERT (2, 'OTHER_OWNER_CATEGORY');

INSERT    INTO ACCOUNT_CATEGORY_FOLLOW (account_id, category_id, followed_date)
VALUES    (1, 1, NOW())  -- category 1 (ACTIONS): account 1 has cards in it
        , (1, 11, NOW()); -- category 11 (OTHER_OWNER_CATEGORY, owned by account 2): account 1 does not have it