CREATE
OR        REPLACE FUNCTION FN_CATEGORY_UPDATE_TIME () RETURNS TRIGGER AS $$
BEGIN
    UPDATE CATEGORY
    SET updated_time = NOW()
    WHERE category_id IN (
        SELECT DISTINCT category_id FROM new_rows
    );
    RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE
OR        REPLACE TRIGGER TR_CATEGORY_UPDATE_TIME
AFTER INSERT ON CATEGORY_CARD_CONTAIN
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT EXECUTE FUNCTION FN_CATEGORY_UPDATE_TIME ();