CREATE
OR        REPLACE FUNCTION FN_CATEGORY_NUM_OF_CARD_INC () RETURNS TRIGGER AS $$
BEGIN
    UPDATE CATEGORY C
    SET numOfCard = C.numOfCard + 1
    WHERE C.category_id IN (SELECT category_id FROM new_rows);
    RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE
OR        REPLACE TRIGGER TR_CATEGORY_NUM_OF_CARD_INC
AFTER INSERT ON CATEGORY_CARD_CONTAIN
REFERENCING NEW TABLE AS new_rows
FOR EACH STATEMENT EXECUTE FUNCTION FN_CATEGORY_NUM_OF_CARD_INC ();

CREATE
OR        REPLACE FUNCTION FN_CATEGORY_NUM_OF_CARD_DEC () RETURNS TRIGGER AS $$
BEGIN
    UPDATE CATEGORY C
    SET numOfCard = GREATEST(C.numOfCard - 1, 0)
    WHERE C.category_id IN (SELECT category_id FROM old_rows);
    RETURN NULL;
END $$ LANGUAGE plpgsql;

CREATE
OR        REPLACE TRIGGER TR_CATEGORY_NUM_OF_CARD_DEC
AFTER DELETE ON CATEGORY_CARD_CONTAIN
REFERENCING OLD TABLE AS old_rows
FOR EACH STATEMENT EXECUTE FUNCTION FN_CATEGORY_NUM_OF_CARD_DEC ();